### ISSUE TITLE
[clarifications] This is not following the BPE paper you've mentioned in encoder.py 

### ISSUE THREAD

**Issue by edoson** [soaxelbrooke/python-bpe#21]
Hi, 

Thanks for the code. Went over it and saw that while the original paper start with set of chars as starting point and combines most frequent symbols till reaching the top K, your implementation seems much different. You start with saving top-words and then adds top bigrams, trigrams etc. In your implementation `UNK` is possible, while in the original paper it is not.. 

Can you explain those choices?

**Comment by soaxelbrooke** [comment]
Hey edoson! Yes, you’re right that this doesn’t directly implement BPE as described in the paper. The differences you described were intentional choices made for the benefit of optimizing its use for text classification tasks, both for increasing the utility of the resulting tokenization and making it more efficient computationally at inference time. Maybe it should be called byte chunk encoding here 😅
